### ISSUE TITLE
无法评论

### ISSUE THREAD

**Issue by Rinfly** [Duanyll/duanyll.github.io#11]
当我使用github登录后，就会出现一个`[object ProgressEvent]`的弹窗，点击确定后评论无法加载。如果刷新就要求重新登录。

**Comment by Rinfly** [comment]
可以我刷新后还是会出现弹窗，评论区会一直加载；重新打开页面就又需要登录

**Comment by Duanyll** [comment]
现在还有锅吗?

**Comment by Rinfly** [comment]
有。不过可以用issues评论

**Comment by Duanyll** [comment]
我知道为什么了

这个Gitment用到的CORS跳转服务的HTTPS证书过期了。。。

**Comment by Duanyll** [comment]
fixed by moving to [utterances](https://utteranc.es/)
