### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by Rinfly** [Duanyll/duanyll.github.io#2]
You say ``this dalao``, that's actually a wrong description of me. You should change the word ``dalao`` to ``juruo`` or ``caiji``, because **I VERY VEGETABLE !!!**

**Comment by Duanyll** [comment]
`dalao` when did you opened this issue? i made no sense of it!
thanks for you suggestions

**Comment by Rinfly** [comment]
The Castersoft.com is Star He's website, it's not mine!

**Comment by Duanyll** [comment]
i know that!
But I cant open his website anymore. maybe he forgets to pay for it.
