### ISSUE TITLE
首页含有不安全的混合内容

### ISSUE THREAD

**Issue by Rinfly** [Duanyll/duanyll.github.io#4]
用FF访问首页会显示含http混合内容，而chrome却没有提示。具体原因不明确。

不过我博客的友链页面有一段时间也是一直这样，后来发现是cyc大佬博客头像被cnblogs跳转到了一个http的图片。

**Comment by Duanyll** [comment]
可能是castersoft与auoj的友链没有HTTPS

**Comment by Duanyll** [comment]
喊hxh把他的HTTPS修好

**Comment by Rinfly** [comment]
仅仅是链接有http应该不会出现这个问题
还有hxh是用的Aliyun主机，我给他申请过一个证书但是不买cdn的话没法部署，您可以给他改成https，只是会有一个警告页就可以照常访问了

**Comment by Duanyll** [comment]
那就很奇怪了，我无法复现这个问题

**Comment by Rinfly** [comment]
我觉得应该是 index.html:25
```js
<script src="https://code.jquery.com/jquery-3.3.0.min.js" integrity="sha256-RTQy8VOmNlT6b2PIRur37p6JEBZUE7o8wPgMvu18MC4="
    crossorigin="anonymous"></script>
```
中``integrity``属性的hash值不正确造成的问题，您可以把除了``src``外的属性删去试试

**Comment by Duanyll** [comment]
没什么动静就关了这个issue
